projectTitle = "VoidLib"
modId = "voidlib"
githubRepo = "TeamVoided/VoidLib"
#Ender's server invite
discordServerInviteId = "KZ5Q364hEg"
authors = [ "brokenfuse", "theendercore" ]
majorMinecraftVersion = "1.20"
minecraftVersion = "1.20.1"
fabricLoaderVersion = "0.14.21"
fabricApiVersion = "0.84.0+1.20.1"
fabricLangKotlinVersion = "1.10.0+kotlin.1.9.0"
license = "MIT"
modules = [ "config", "core", "cresm", "dimutil", "pow", "vui", "wfc", "woodset" ]

[mappings]
    type = "YARN"
    version = "1.20.1+build.9"