projectTitle = "Voidlib"
modId = "voidlib"
modVersion = "0.1.0-alpha.1"
group = "org.teamvoided"
githubRepo = "TeamVoided/VoidLib"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TeamVoided", "TheEnderCore" ]
majorMinecraftVersion = ">=1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.16.14"
fabricApiVersion = "0.116.0+1.21.1"
fabricLangKotlinVersion = "1.13.2+kotlin.2.1.20"
license = "MIT"
modules = [ "voidmill", "voidcore", "vtags", "headless" ]
modDescription = "A collection of libraries for moding minecraft."
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ "library" ]
disableKotlin = false

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "QUILT"
    version = "1.21.1+build.9"